config/routes.rb
Rails.application.routes.draw do
	root 'carts#index'
  
  devise_for :users
  
  resources :carts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :authenticate_user!

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :wallet, :shoes, :shirt, :age])
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :set_cart, only: [:show,:edit,:update,:destroy]
  def index
  	@carts = current_user.carts.all
  end

  def show
  end

  def new
  	@cart = current_user.carts.new
  end

  def create
  	@cart = current_user.carts.new(cart_params)
  	if @cart.save
  		redirect_to root_path
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @cart.update(cart_params)
  		redirect_to root_path
  	else
  		render :edit
  	end
  end

  def destroy
  	@cart.destroy
  	redirect_to root_path
  end

  private
  def set_cart
  	@cart = current_user.cart.find(params[:id])
  end

  def cart_params
  	params.require(:cart).permit(:total)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/index.html.erb
<%= button_to 'Log out', destroy_user_session_path, method: :delete %>
<h1>Cart</h1>
<h3>Welcome <%= current_user.name %></h3>
<h3>Wallet Amount: $<%= current_user.wallet %></h3>

<%= link_to 'Add Cart', new_cart_path %>

<p>
	<%= current_user.shoes ? 'Nice shoes!' : '' %>
</p>

<p>
	<%= current_user.shirt ? '' : 'Put on a shirt you bum!' %>
</p>

<p>Cart</p>
<% @carts.each do |c| %>
	<%= c.total %>
<% end %>

app/views/carts/new.html.erb
<h1>New Cart</h1>
<%= form_with(model: @cart, local: true) do |f| %>
	<div class="field">
		<%= f.label :total %>
		<%= f.number_field :total, min: 0, step: 0.01 %>

		<%= f.submit %>
	</div>
<% end %>

app/views/carts/show.html.erb
<h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>